### ISSUE TITLE
Add button to hide DLC

### ISSUE THREAD

**Issue by AxelGuarneros** [tralph3/Steam-Metadata-Editor#12]
All DLC have the edit launch menu greyed out but it would help to have a button to be able either to hide or display the DLC.

This would help fix some games that detects the erroneous DLC and fails to boot up.

**Comment by tralph3** [comment]
Hmmm... such as? I don't see how hiding the DLC will make a game not detect it.

**Comment by AxelGuarneros** [comment]
Assassin's Creed II and Assassin's Creed Brotherhood.
There are some people already using this tool but with workarounds like [this one](https://github.com/ValveSoftware/steam-for-linux/issues/5649#issuecomment-829708680) to solve the issue.

**Comment by tralph3** [comment]
Apparently it didn't solve the issue right? I saw that Assassin's Creed thread a while ago, you're setting the wrong thing on the file. According to that post, you should be setting the `showcdkeyonlaunch` var to `0` on the `extended` section. I believe this is a setting that's going to be used to sparsely that it's better off to just let it sit as a modification you can do through the JSON.
