### ISSUE TITLE
Change game description?

### ISSUE THREAD

**Issue by Oondanomala** [tralph3/Steam-Metadata-Editor#17]
Is it possible to change a game description?
That would be especially useful with non steam games (tho those aren't supported atm)

**Comment by tralph3** [comment]
Hi. The game description's aren't stored in the appinfo file, so I would need to use some different method to change those, which is currently not in the plans. As for non-steam games, same deal, their data is stored elsewhere. I don't even think it's possible to add descriptions for non-steam games, even in non-official manners.

So, sorry, but we're out of luck on this one :(
