### ISSUE TITLE
Possibility of changing platform for a game?

### ISSUE THREAD

**Issue by parkerlreed** [tralph3/Steam-Metadata-Editor#21]
Trying to edit the manifest of Beam.NG to make it think it has native Linux support. 

Beam.NG has a launch option for the Linux beta but since its a Windows only game, never shows it. 

I manually removed both of the Windows options with Steam Metadata Editor but then it tries running the Linux binary with WINE. 

![image](https://user-images.githubusercontent.com/841440/190237846-97287e1f-7d97-4c28-a869-d7d15f71aa22.png)

![image](https://user-images.githubusercontent.com/841440/190237866-ec72b1bc-cb27-48b5-8519-1a4f9cd58ef6.png)

As a last resort I tried forcing Steam Linux Runtime from ProtonUP-QT but then it just thinks the game is uninstalled.

Would be greet to set the overall game platform as well from within Steam Metadata Editor

**Comment by tralph3** [comment]
Hi, I explained why this doesn't work here: https://github.com/tralph3/Steam-Metadata-Editor/issues/20#issuecomment-1193237623

In short, in order for a launch option for a particular platform to show, the game must support that platform (i.e, have a depot for it). Beamn.NG does have an experimental Linux binary, but it comes with the Windows version, there's no Linux depot as seen here: https://steamdb.info/app/284160/depots/

So there's nothing really I can do. Steam will *always* try to run it with Proton. The only solution would be to find a way to tell Proton to run it as a Linux executable, but I'm not aware of a solution for that.
