### ISSUE TITLE
Error on Windows when editing launch entries.

### ISSUE THREAD

**Issue by nl255** [tralph3/Steam-Metadata-Editor#31]
When I run steam metadata editor on Windows (haven't tried it on the deck yet) everything seems to work fine but when editing an entry I get this error message.

`Exception in Tkinter callback
Traceback (most recent call last):
  File "e:\python\python392\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "L:\z.gamesavebackup\0-steam-metadata-editor\gui\main_window.py", line 940, in <lambda>
    command=lambda: self.generate_launch_option_string(
  File "L:\z.gamesavebackup\0-steam-metadata-editor\gui\main_window.py", line 851, in generate_launch_option_string
    wkngDirVar = wkngDirVar.replace("/", "\\")
AttributeError: 'StringVar' object has no attribute 'replace'`

**Comment by tralph3** [comment]
There was a problem with the backslashes. I just pushed a commit that should fix the issue, please try it.

**Comment by nl255** [comment]
It seems to be working fine now on Windows, still need to see if it does the right thing on the Steam Deck (since while it runs Linux most of the games are for Windows and thus using Windows executable launch entries).

**Comment by tralph3** [comment]
The problem was with the way Windows handles paths, which uses backslashes, and the way Linux handles them, which is with forward slashes. It has nothing to do with the platform of each particular game, it should work just fine.

I'll be closing this now.
