### ISSUE TITLE
Unable to find config files in flatpak installation (Steam Deck)

### ISSUE THREAD

**Issue by olee** [tralph3/Steam-Metadata-Editor#33]
Hi, I tried running the flatpak installation for this app on the steam deck, however I cannot find out where this app saves the config files to make the changes I need.
I checked in `./local/share/Steam-Metadata-Editor`, but the directory does not even exist and I was not able to find any other location where it could be.

**Comment by tralph3** [comment]
Flatpak creates an environment in `~/.var/app/io.github.tralph3.Steam_Metadata_Editor` but I can't find the modifications json there...

I have deleted the folder in `~/.local/share`, re-run SME with flatpak, made some modifications, and sure enough, there's no folder in `~/.local/share`, so it's storing them somewhere else.

I ran `updatedb` and then `locate` to try and find it, but it couldn't. So I must assume it's not stored with the regular name, it must be encrypted in some way.

If anyone knows how flatpak manages these things, please let me know, I'm kinda puzzled about it.

**Comment by olee** [comment]
I found the solution:
I used Flatseal to adjust the permissions of the application to include `~/.local/share/Steam-Metadata-Editor` as allowed file access location and then it worked!
Seems like whoever setup the configuration [here](https://github.com/flathub/io.github.tralph3.Steam_Metadata_Editor) didn't add this path to the config.

**Comment by tralph3** [comment]
My bad! I have updated the manifest to allow access to that folder. This shouldn't be an issue anymore.
