### ISSUE TITLE
CLI support

### ISSUE THREAD

**Issue by CovertDuck** [tralph3/Steam-Metadata-Editor#34]
Is CLI support on the roadmap? I would love to push a PR for it if doing so doesn't spell maintainability issues in the future. Basic arguments support shouldn't be too much of an issue to implement. Some interactivity (like rclone's configuration utility for lack of a better example) would also be feasible, although this might be reinventing the wheel a little bit as we already have a functional GUI.

**Comment by tralph3** [comment]
You can kinda do it already by modifying the `modifications.json` with something like `jq`, then running `steammetadataeditor -s`. No GUI required, and it's transparent.

Honestly, I don't know what kind of CLI interface I could provide. Best I can come up with is maybe read a json from STDIN and apply it to a specific app, but modifying the JSON itself is already done better by other programs.

If you have any specific feature in mind, do tell!

**Comment by CovertDuck** [comment]
Main use case I had in mind was managing my metadata between multiple Steam installations with cleaned up, human-readable JSON "profiles".

That could be done with the GUI as well, but being able to load up and apply full or partial metadata with the CLI could be useful.

Parsing and piping metadata to another program could also be nifty.

Eventually, I would love to come up with a community, cleaned up and "updated" VDF file to share around. Being able to import/export with either a GUI or the CLI could help things move along if multiple people are to contribute to such a project.

**Comment by CovertDuck** [comment]
Also, I just hate how Tkinter looks. But that's more of a me problem. :p

**Comment by CovertDuck** [comment]
Closing in favor of #35, which is a far more sensible feature.
