### ISSUE TITLE
Two general issues I've found so far.

### ISSUE THREAD

**Issue by Synkro12** [tralph3/Steam-Metadata-Editor#4]
Hi there, I've found two issues so far.

1. SME does not apply edits correctly unless silent patching is used, to elaborate, when using the GUI, making edits and then clicking save, only the last edit you made will have a 50/50 chance of being applied, when making edits to multiple games, saving, then using the silent patching all edits apply as they should.

2. SME seems to be unable to handle multiple devolpers/publishers, other edits apply normally, but any edits that initially had multiple values don't. https://imgur.com/17dJigX

Also to add, a filter would be much appreciated, i.e filtering out DLC or Tools.

**Comment by tralph3** [comment]
Thanks! I've got to say that the multiple developers/publishers thing is an oversight on my part, I didn't relize there were multiple for some games. Anyways, I'll have to add that. As for the changes not getting applied sometimes... I'll have to look into that, but are you sure it's SME not applying them, and not Steam reverting the changes? If when you load up Steam you see a "Updating User Configuration" window, and the progress bar fills up gradually (i.e., it doesn't instantly close or go from 0% to 100%) then Steam is reverting the changes. If that's the case, there's not much I can do about it. As for why silent patching seems to be more consistent, no idea, both the save button and silent patching use the same functions but I'll take a look and see what I can do.

As for filters, noted, I should add something like that.

**Comment by Synkro12** [comment]
Yeah, to elaborate a bit further cause I did some more testing, SME seems to apply one edit, as I get that little "Updating User Configuration" window you mentioned.

For example, say I edit both the name of something, and it's sort name, if I changed the sort name last, only that edit would apply to Steam, but SME would still save both changes to the json file, the point about silent patching working with everything still stands there.

Oh and to add on to the multiple devs/publishers, I can add multiple, using a comma to seperate them and it works fine, it's just the games that already have multiple devs/publishers that have said issue.

**Comment by tralph3** [comment]
I just tested it with The Binding of Isaac Rebirth. I changed the name, the sort as string, the publisher and the developer. Both publisher and developer weren't applied with or without silent patching for some reason, but the other two did get applied without silent patching needed. The "only applies the last change" doesn't seem to be true. I also tried to change multiple games at once, and it also worked, so the issue seems to be improperly handling some entries.

Could you specify which games don't seem to apply all the paramters? If you think the sort as string isn't getting respected, check the games above it, they may have other sort as strings that would actually put them above the game you modified.

**Comment by Synkro12** [comment]
Hey there, sorry about the late reply, while I don't own The Binding of Isacc, I've been trying to get this issue to reliably happen to no avail, regular saving seems to work now for some reason, and silent patching is still working, though like you said Devolper and Publisher don't seem to work for me either.

My Entire library was having issues so I'd rather not type it out, since the issues that are happening seem to have rhyme or reason to it.

**Comment by Synkro12** [comment]
I don't think I'd have to, SME is working fairly consistently now, it's just that I can't reproduce that bug reliably.
