### ISSUE TITLE
[Feature Request] Non Steam Games Editing

### ISSUE THREAD

**Issue by Dimolade** [tralph3/Steam-Metadata-Editor#48]
So i'm trying to Install ModManager2 for Fallout: New Vegas but it only works for the steam version which i don't have so iv'e added Fallout: New Vegas to Steam. I wanted to change it ID to the original AppID so that it would work. But i couldnt find the Game.

**Comment by tralph3** [comment]
The way non Steam games are stored is completely different to that of regular ones. As such, supporting it is a non-trivial task I'm not willing to take on right now.

Plus, I don't think changing the ID is possible.
