### ISSUE TITLE
New Steam Beta changed VDF version

### ISSUE THREAD

**Issue by TheConfuZzledDude** [tralph3/Steam-Metadata-Editor#51]
The latest Steam Client Beta has apparently bumped the version of the VDF to 0x107564429, so it's no longer supported by this program :/

**Comment by tralph3** [comment]
Just including the new version number in the supported versions doesn't work. The format did change. I don't have the time to figure out what actually changed right now, so I'll have to wait until [xPaw](https://github.com/SteamDatabase/SteamAppInfo) documents it.

**Comment by TheConfuZzledDude** [comment]
I imagine it's related to the games's compatibility with the new game recording feature

**Comment by tralph3** [comment]
Can't be that, it'd be a new entry in the app's dictionary, which should be parsed without issues.

**Comment by TheConfuZzledDude** [comment]
Ah xPaw has documented it, seems like just a table of strings has been added

**Comment by tralph3** [comment]
Cool, I'll look into it in a bit.

**Comment by tralph3** [comment]
New version is supported now (hopefully without bugs).
