### ISSUE TITLE
not using selected executable

### ISSUE THREAD

**Issue by mattsplanet** [tralph3/Steam-Metadata-Editor#52]
i'm trying to add the seamless coop mod to my launch options 

![image](https://github.com/tralph3/Steam-Metadata-Editor/assets/174357136/47339077-40be-4ea5-8fd4-385e4e7afdb0)
![image](https://github.com/tralph3/Steam-Metadata-Editor/assets/174357136/ff0bee03-ecd9-401e-a331-1474ccd5f215)

the problem i am having is that even though the option is being added to the list and is set to use the seamless .exe it uses the default elden ring one regardless

![image](https://github.com/tralph3/Steam-Metadata-Editor/assets/174357136/00c4374f-fe29-4854-a953-0f3c6b1d80fa)

is there something i'm doing wrong here or is this a problem with the mod executable?

**Comment by tralph3** [comment]
If the launch option is being added to the game, then there's not much else SME can do.

I wonder if it has to do with using backslashes for the game path...

One thing yo can try is to drop the seamless coop launcher in the parent ELDEN RING folder, and leave the working directory inside the Game folder.

That way there will be no backslashes in either the executable or working directory path.

If that ends up working, I'll submit a patch to use forward slashes on Windows as well.

**Comment by mattsplanet** [comment]
the exe won't run unless it is in the game folder because it needs the eldenring.exe which needs all of the other game files

**Comment by tralph3** [comment]
That's what the working directory entry is for.

**Comment by mattsplanet** [comment]
no, it still acts as if i was launching eldenring.exe not ersc_launcher.exe

**Comment by tralph3** [comment]
Ok to rule out any issue SME may be having, create a text file with the following contents:

    @echo off
    title Countdown Timer
    echo Counting down...
    for /l %%i in (5,-1,1) do (
        echo %%i
        ping localhost -n 2 >nul
    )
    echo Done!
    pause

Save the file as "test.bat", very important that the extension is .bat.

Then use SME to make Steam launch this file. The script should open a terminal window counting down from 5 to 1, it doesn't do anything, it's simply there to check that Steam is launching the correct file.

If this works, then SME is not at fault, it's the exe that has something wrong, and I can do nothing to solve the issue.

**Comment by mattsplanet** [comment]
yeah that worked fine so it's a seamless issue, no worries, thanks for trying regardless
