### ISSUE TITLE
Create/update modification.json from cli parameters

### ISSUE THREAD

**Issue by NathanaelA** [tralph3/Steam-Metadata-Editor#6]
This is like #5 other than I want to have it be "targeted" to a single game id.  I'd like to be able to do something like `steammetadataeditor -m <steamid>` and it would create both the original & modified section in the modification.json file just like it does now when you make a change and click the save button.      Then I can use something like `jq` to make the changes to the json, and finally do a `steammetadataeditor -s` to apply them.    

My objective would be:
- export a specific games json, then parse it using JQ to read all DLC ids
- export all the DLC's ids the same way
- apply the `showcdkeyonlaunch: 0` to all DLC and the main game
- apply the new "changed" json back to steam.

This would be very useful because certain games on linux the `showcdkeyonlaunch` creates a issue where the game can't run.   So if I can easily script a script to export out any of the games that I'm having this issue and the dlc (as the dlc with this flag will also cause the exact same issue).    And then have `jq` make all the changes, then I could have  a simple script: `fix_steam_game <id>` and it would apply this fix to everything.   

So the only feature that is really missing in this whole thing is the cli export of a game entry...

**Comment by tralph3** [comment]
Ah that shouldn't be hard to do. If I have some time later today I might add it. Thanks for the suggestion!

**Comment by tralph3** [comment]
I just pushed an update that should let you do what you want. Just pass the -e argument with the list of appIDs you want exported and it should do the job.

    steammetadaeditor -e 3123 13545 1223415 4323

Please tell me if it has issues.

**Comment by mirh** [comment]
What if there was some `reg.exe`-like syntax for manipulations from cli?
E.g. REG QUERY, REG ADD and REG DELETE.

**Comment by tralph3** [comment]
I had planned to overhaul the program and it would allow for such a thing by passing json's as arguments. There's no ETA on that tho.

**Comment by mirh** [comment]
Passing files seems far more involved and less immediate than what I was suggesting (even though sure, it has its occasions). 
`steammetadaeditor [-a|add] 3123 showcdkeyonlaunch 0` seems as easy as you could get instead.

**Comment by tralph3** [comment]
That alone wouldn't work. How do we know where to drop that key? You would need to provide the full structure of the metadata.

Maybe we can separate each key by dots or something? So:

    steammetadaeditor [-a|add] 3123 common.showcdkeyonlaunch 0

**Comment by mirh** [comment]
Oh, I see sorry. I didn't think there were "parallel sub-sections". 
That works for me (and it may even make for more clarity when you tinker with stuff outside of appinfo.vdf)
